//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public Allocation()
        {
            this.ProductAllocations = new HashSet<ProductAllocation>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int ProductId { get; set; }
        public int ProductCount { get; set; }
        public int ManufacturerId { get; set; }
        public int VendorId { get; set; }
        public bool IsSplit { get; set; }
        public System.DateTime LastEditDateTime { get; set; }
        public string LastEditUser { get; set; }
    
        public virtual ICollection<ProductAllocation> ProductAllocations { get; set; }
    }
}
