//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocationLot
    {
        public AllocationLot()
        {
            this.Returns = new HashSet<Return>();
        }
    
        public int Id { get; set; }
        public int AllocationId { get; set; }
        public int LotId { get; set; }
        public int Quantity { get; set; }
        public string LastEditUser { get; set; }
        public System.DateTime LastEditDateTime { get; set; }
    
        public virtual Allocation Allocation { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual ICollection<Return> Returns { get; set; }
    }
}
