//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITInventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITInventoryEntities : DbContext
    {
        public ITInventoryEntities()
            : base("name=ITInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AllocationOffice> AllocationOffices { get; set; }
        public DbSet<Kit> Kits { get; set; }
        public DbSet<KitProduct> KitProducts { get; set; }
        public DbSet<Lot> Lots { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Return> Returns { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<Allocation> Allocations { get; set; }
        public DbSet<AllocationLot> AllocationLots { get; set; }
        public DbSet<OrderProduct> OrderProducts { get; set; }
    }
}
