//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductAllocations = new HashSet<ProductAllocation>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string SKU { get; set; }
        public decimal SellPrice { get; set; }
        public int Weight { get; set; }
        public string WeightUnit { get; set; }
        public int PackageWeight { get; set; }
        public int PackageHeight { get; set; }
        public int PackageLength { get; set; }
        public int PackageUnits { get; set; }
        public int QtyPerPackage { get; set; }
        public int DefaultOrderSize { get; set; }
        public int ManufacturerId { get; set; }
        public int VendorId { get; set; }
        public string ImagePath { get; set; }
        public int OnOrder { get; set; }
        public string Catalog { get; set; }
        public int StockLevel { get; set; }
        public int ReorderThreshold { get; set; }
        public Nullable<int> KitId { get; set; }
        public bool Active { get; set; }
        public System.DateTime LastOrderedDate { get; set; }
        public System.DateTime LastEditDateTime { get; set; }
        public string LastEditUser { get; set; }
    
        public virtual Kit Kit { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Vendor Vendor1 { get; set; }
        public virtual ICollection<ProductAllocation> ProductAllocations { get; set; }
    }
}
