//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDB_HDC_OFFICEINFO
    {
        public int RSCDB { get; set; }
        public Nullable<int> EpicorID { get; set; }
        public string OfficeName { get; set; }
        public string FormalName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Corp { get; set; }
        public Nullable<short> SpeedDial { get; set; }
        public string OfficeType { get; set; }
        public string ConsID { get; set; }
        public string RA_ID { get; set; }
        public string VP { get; set; }
        public string PA { get; set; }
        public string OM { get; set; }
        public string NewRDO { get; set; }
        public string NewRA { get; set; }
        public string CA { get; set; }
        public string Accounting { get; set; }
        public string AP { get; set; }
        public string AR { get; set; }
        public string Mktg { get; set; }
        public string Payroll { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<decimal> NumDrs { get; set; }
        public string Press_Ganey { get; set; }
        public Nullable<decimal> ThriveGoal { get; set; }
        public Nullable<int> ChairsAvail { get; set; }
        public Nullable<int> PotentialChairs { get; set; }
        public string TFGroup { get; set; }
        public Nullable<decimal> ContMargin { get; set; }
        public string OfficeClass { get; set; }
        public string G4 { get; set; }
        public Nullable<System.DateTime> G5Date { get; set; }
        public string XRay { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> ConversionDate { get; set; }
        public Nullable<decimal> DaysBfHDC { get; set; }
        public Nullable<decimal> DaysAfterHDC { get; set; }
        public Nullable<decimal> FirstMthDaysMissed { get; set; }
        public Nullable<decimal> LastMthDaysMissed { get; set; }
        public Nullable<int> MergedInto { get; set; }
        public Nullable<int> Biolase { get; set; }
        public Nullable<System.DateTime> Accelerate { get; set; }
        public Nullable<System.DateTime> Catapult { get; set; }
        public Nullable<int> SqFoot { get; set; }
        public string PrevName { get; set; }
        public string OfficeEMail { get; set; }
        public Nullable<bool> SimpleDental { get; set; }
        public Nullable<bool> Fortiva { get; set; }
        public string CareCreditID { get; set; }
        public string AllianceData { get; set; }
        public Nullable<System.DateTime> FirstMonth { get; set; }
        public string OfficeURL { get; set; }
        public string SRDO { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string FacebookURL { get; set; }
        public string CareCreditURL { get; set; }
        public string GooglePlusURL { get; set; }
        public string GoogleAnalytics { get; set; }
        public string DMA { get; set; }
        public string DrivingDirections { get; set; }
        public string TwoXTwoXTwo { get; set; }
        public string SrRA { get; set; }
        public string PCInfo { get; set; }
        public string NewSrRA { get; set; }
        public Nullable<int> NPPrediction { get; set; }
        public Nullable<int> PlannedHireDR { get; set; }
        public Nullable<int> PlannedHireHYG { get; set; }
        public Nullable<int> PlannedHireDA { get; set; }
        public Nullable<int> PlannedHireBA { get; set; }
        public Nullable<int> PlannedHireOM { get; set; }
        public Nullable<int> CurrentHireDRExp { get; set; }
        public Nullable<int> CurrentHireDRNewGrad { get; set; }
        public Nullable<int> CurrentHireDR { get; set; }
        public Nullable<int> CurrentHireHYG { get; set; }
        public Nullable<int> CurrentHireDA { get; set; }
        public Nullable<int> CurrentHireBA { get; set; }
        public Nullable<int> CurrentHireOM { get; set; }
        public Nullable<int> CallsFromNewPatients { get; set; }
        public Nullable<int> NewPatientsScheduled { get; set; }
        public string MarketingDetails { get; set; }
        public string MarketingDirectMail { get; set; }
        public Nullable<int> MondayOpen { get; set; }
        public Nullable<int> MondayClose { get; set; }
        public Nullable<int> TuesdayOpen { get; set; }
        public Nullable<int> TuesdayClose { get; set; }
        public Nullable<int> WednesdayOpen { get; set; }
        public Nullable<int> WednesdayClose { get; set; }
        public Nullable<int> ThursdayOpen { get; set; }
        public Nullable<int> ThursdayClose { get; set; }
        public Nullable<int> FridayOpen { get; set; }
        public Nullable<int> FridayClose { get; set; }
        public Nullable<int> SaturdayOpen { get; set; }
        public Nullable<int> SaturdayClose { get; set; }
        public Nullable<int> SundayOpen { get; set; }
        public Nullable<int> SundayClose { get; set; }
        public Nullable<bool> ExtendedHours { get; set; }
        public Nullable<double> TotalHoursMonFri { get; set; }
        public Nullable<double> TotalHoursMonSun { get; set; }
        public Nullable<System.DateTime> DateOf1st40HourWeek { get; set; }
        public string ScheduleNotes { get; set; }
        public Nullable<int> AccessToCareCurrentWeek { get; set; }
        public Nullable<int> AccessToCarePriorWeek { get; set; }
        public Nullable<int> AccessToCare2WeeksPrior { get; set; }
        public string PracticeManagementSoftware { get; set; }
        public Nullable<bool> SpecialtyEndo { get; set; }
        public Nullable<bool> SpecialtyOralSurgery { get; set; }
        public Nullable<bool> SpecialtyOrtho { get; set; }
        public Nullable<bool> SpecialtyPedo { get; set; }
        public Nullable<bool> SpecialtyPerio { get; set; }
        public Nullable<bool> PSRSupported { get; set; }
        public string MarketingWebsite { get; set; }
        public string PSRSupervisor { get; set; }
        public Nullable<decimal> FullFeeFor59DollarIncentive { get; set; }
        public string PSROnlineAppointmentRequestStatus { get; set; }
        public Nullable<decimal> PSRProviderHours { get; set; }
        public Nullable<decimal> DMP5YearNetProductionGoal { get; set; }
        public string DentrixCustomerNumber { get; set; }
        public Nullable<bool> HealthGradesParticipant { get; set; }
        public string CommunicationVendor { get; set; }
        public string ClinicalSuppliesRepresentative { get; set; }
        public string TeamRecruiter { get; set; }
        public string ProjectManager { get; set; }
        public Nullable<decimal> AffiliationProForma { get; set; }
        public Nullable<decimal> AffiliationProFormaEBITDA { get; set; }
        public string MarketingRepManager { get; set; }
        public string RSA { get; set; }
        public Nullable<int> Exclusions { get; set; }
        public string IPAddress { get; set; }
        public string DMPEnrollment { get; set; }
        public string DNI { get; set; }
        public string DAT { get; set; }
        public string Landlord { get; set; }
        public string DXOneAPIStatus { get; set; }
        public Nullable<System.DateTime> DXOneAPIGoLiveDate { get; set; }
        public string SeniorTeamRecruiter { get; set; }
    }
}
